# Generated by Django 6.0.6 on 2026-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('pacientes_criticos', models.IntegerField(default=0)),
                ('pacientes_hipertensos', models.IntegerField(default=0)),
                ('pacientes_diabeticos', models.IntegerField(default=0)),
                ('pacientes_fumadores', models.IntegerField(default=0)),
                ('pacientes_obesos', models.IntegerField(default=0)),
                ('pacientes_antecedentes', models.IntegerField(default=0)),
                ('pacientes_alcohol', models.IntegerField(default=0)),
                ('pacientes_saturacion_baja', models.IntegerField(default=0)),
                ('riesgo_promedio', models.FloatField(default=0.0)),
                ('alertas_sistolica', models.IntegerField(default=0)),
                ('alertas_glucosa', models.IntegerField(default=0)),
                ('alertas_saturacion', models.IntegerField(default=0)),
                ('edad_media', models.FloatField(default=0.0)),
                ('edad_mediana', models.FloatField(default=0.0)),
                ('edad_moda', models.FloatField(default=0.0)),
                ('edad_desviacion', models.FloatField(default=0.0)),
                ('glucosa_media', models.FloatField(default=0.0)),
                ('glucosa_desviacion', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='ETLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fase', models.CharField(default='', max_length=32)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('detalle', models.TextField(blank=True, default='')),
                ('logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
