# Generated by Django 6.0.6 on 2026-06-22 15:32

from django.db import migrations, models


def convertir_sexo(apps, schema_editor):
    Paciente = apps.get_model('etl', 'Paciente')
    mapping = {'M': 'Masculino', 'F': 'Femenino', 'O': 'Otro'}
    for old, new in mapping.items():
        Paciente.objects.filter(sexo=old).update(sexo=new)


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_dashboardkpis_etltask'),
    ]

    operations = [
        migrations.RunPython(convertir_sexo, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10, null=True),
        ),
    ]
