# Generated by Django 4.2.30 on 2026-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_sexo_full_strings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='frecuencia_cardiaca',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_diastolica',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='presion_sistolica',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
